name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '21 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: |
        version=dev
        # mvn -B -f pom.xml clean package -Ddoc.version=$version
        ./substitute.sh ${version}
        docker run -v .:/doc -u $(id -u) axonivy/build-container:read-the-docs-2 make html BASEDIR=/doc
        rm build/html/portal-guide/index.html
    - name: Archive build artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          build/html/**/*
